### ISSUE TITLE
Extensão `.comp`

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#1]
https://github.com/Alexia-Passos/telavitaChallenge/blob/52455af4e4718b819979985b9aca158125e0ab35/src/components/home/home-pagination/home-pagination.jsx#L1-L22

Boa tarde Alexia, tudo bem?

Percebi que nos demais arquivos que contém componentes você escolheu utilizar a extensão `.comp` mas neste não.

Qual é a motivação da utilização da extensão `.comp` e por que este arquivo foi deixado sem?

Obrigado :)

**Comment by Alexia-Passos** [comment]
Boa tarde! Tudo ótimo e você? 
A princípio a lógica desse componente estava dentro da Home, e no último momento fiz a separação do component por entender que em outro contexto ele poderia ser reutilizado, mas não me atentei ao padrão.

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
