### ISSUE TITLE
logo_telavita.jpg, background2.webp, background3.webp

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#2]
Boa tarde Alexia, tudo bem?

Percebi que temos esses 3 arquivos na pasta `/public`.

Qual seria a utilidade deles?

Obrigado :)

**Comment by Alexia-Passos** [comment]
Foi desatenção mesmo! Geralmente ao terminar algum projeto pessoal, ou nesse caso um desafio, eu passo revisando todos os diretórios e revendo o que faz sentido ou não manter, e como fiz com um pouco de pressa a revisão, passou batido.

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
