### ISSUE TITLE
`await` junto com `then`

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#3]
https://github.com/Alexia-Passos/telavitaChallenge/blob/52455af4e4718b819979985b9aca158125e0ab35/src/pages/home-page/Home.js#L72

Boa tarde Alexia, tudo bem?

Percebi que escolheu utilizar o `await` juntamente com o `then`.

Qual seria o objetivo de utilizar ambos?
Qual é o efeito que isso tem na aplicação?

Obrigado :)

**Comment by Alexia-Passos** [comment]
Sinceridade? Eu tava tendo dificuldade com o tempo do retorno dos dados, estava chegando undefined. Encontrei um professor ensinando dessa forma, e funcionou! Então na ausência de uma solução melhor, optei por essa com menos sentido.

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
