### ISSUE TITLE
Categorias de "cards" e `renderType`

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#4]
https://github.com/Alexia-Passos/telavitaChallenge/blob/52455af4e4718b819979985b9aca158125e0ab35/src/pages/home-page/Home.js#L103-L122

Boa tarde Alexia, tudo bem?

Percebi que foi além dos requisitos do desafio e listou não só animes, como também mangas, na mesma página, parabéns!

Caso tivéssemos o requisito de listar mais uma categoria de "card", como adaptaria o `renderType`, que suporta apenas `true` ou `false`, para cobrir este requisito?

Obrigado :)

**Comment by Alexia-Passos** [comment]
Valeu! 
Eu vi que a API retorna um atributo de type, como referência do que é manga ou anime, provavelmente eu faria a verificação por ele.

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
