### ISSUE TITLE
`yarn.lock` e `package-lock.json`

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#5]
Boa tarde Alexia, tudo bem?

Percebi que seu projeto possui tanto `yarn.lock` quanto `package-lock.json`.

Qual é a utilidade de cada um deles e quais são os perigos de mantermos os dois arquivos no projeto?

Obrigado :)

**Comment by Alexia-Passos** [comment]
São arquivos que contém as configurações e dependências do projeto, e eu poderia ter deixado so na minha máquina. Para ser sincera até você me apontar essa questão eu não sabia que ao subir essas configurações fica passível de alteração, o que não aconteceria se eu tivesse adicionado esses arquivos no .gitignore!

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
