### ISSUE TITLE
Título de card "cortado"

### ISSUE THREAD

**Issue by rafaelcanovas** [Alexia-Passos/telavitaChallenge#6]
Boa tarde Alexia, tudo bem?

Percebi que alguns cards acabam ficando com o título cortado, por exemplo:

![Captura de Tela 2022-10-27 às 17 51 40](https://user-images.githubusercontent.com/1323876/198395593-97241bc2-b964-4c62-afbf-3160cba0e0c7.png)

Na sua opinião, o que causa isso e como podemos resolver?

Obrigado :)

**Comment by Alexia-Passos** [comment]
Eu coloquei um tamanho fixo e a informação ficou cortada por isso. 
Poderia ter colocado um valor "auto" para pegar o tamanho de acordo com o tamanho que viesse.

**Comment by rafaelcanovas** [comment]
Obrigado Alexia!
